[build]
  publish = "public/"
  command = "hugo --gc --enableGitInfo"

[build.processing]
  # If skip_processing = true, all other settings in this section are ignored
  skip_processing = true
[build.processing.css]
  # bundle = false
  # minify = false
[build.processing.js]
  # bundle = false
  # minify = false
[build.processing.html]
  # pretty_urls = false
[build.processing.images]
  # compress = false

[context.production.environment]
  TZ = "UTC"
  HUGO_VERSION = "0.101.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"



[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

# Headers and Caching
[[headers]]
  for = "/*"
  [headers.values]
    # Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-protection = "1; mode=block"  
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    # Please cache this content, and then do not trust your cache
    Cache-Control = "max-age=0, must-revalidate, public"

# 7 days (604800 sec)
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "max-age=604800, public, immutable"

# 31 days (2678400 sec)
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "max-age=2678400, public, immutable"